#!/bin/bash

echo "🔐 Admin User Setup Instructions"
echo "================================="
echo ""
echo "📧 Admin Email: peternondo1@gmail.com"
echo ""
echo "🔥 Step 1: Go to Firebase Console"
echo "   https://console.firebase.google.com/project/giftedsolutions-53124/authentication/users"
echo ""
echo "👤 Step 2: Check if user exists"
echo "   - Look for: peternondo1@gmail.com"
echo ""
echo "➕ If user DOESN'T exist:"
echo "   1. Click 'Add user' button"
echo "   2. Email: peternondo1@gmail.com"
echo "   3. Password: [Choose a secure password]"
echo "   4. Click 'Add user'"
echo ""
echo "🔄 If user EXISTS but you forgot password:"
echo "   1. Click the three dots (...) next to the user"
echo "   2. Select 'Reset password'"
echo "   3. Copy the reset link"
echo "   4. Open link in browser"
echo "   5. Set new password"
echo ""
echo "🔑 Or use 'Forgot Password?' on login page:"
echo "   1. Go to: https://giftedsolutions-53124.web.app/admin"
echo "   2. Enter: peternondo1@gmail.com"
echo "   3. Click 'Forgot Password?'"
echo "   4. Click 'Send Reset Email'"
echo "   5. Check peternondo1@gmail.com inbox"
echo "   6. Click reset link in email"
echo "   7. Set new password"
echo ""
echo "✅ After setting password:"
echo "   1. Go to: https://giftedsolutions-53124.web.app/admin"
echo "   2. Email: peternondo1@gmail.com"
echo "   3. Password: [Your new password]"
echo "   4. Click 'Sign In'"
echo ""
echo "🐛 Debug Console:"
echo "   - Press F12 to open browser console"
echo "   - Watch for login debug logs"
echo "   - Look for errors if login fails"
echo ""

